# Generated by Django 5.0.6 on 2024-06-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandatoaporte',
            name='monto',
            field=models.IntegerField(),
        ),
    ]
